### ISSUE TITLE
Error unmounting overlay: invalid argument

### ISSUE THREAD

**Issue by matbme** [Vanilla-OS/almost#1]
I created an overlay at /usr/lib/ for installing some files required for my webcam driver, but now I want to discard it but when I run `sudo almost overlay discard /usr/lib/` I get the following error:

![Screenshot from 2022-10-26 08-16-22](https://user-images.githubusercontent.com/48367298/198012791-2ea14d0f-3afd-4f79-8359-57e42a2ccca9.png)

I checked the function responsible for discarding overlays and the problem seems to be related to the arguments passed to umount with `unix.Unmount(path, 0)`, but I'm not familiar enough with Go to pinpoint exactly what.

**Comment by matbme** [comment]
I can also see that `/usr/lib/` isn't listed as a mount point when I run `mount -l`, so it seems that almost either failed to mount it in the first place or it unmounted successfully and failed elsewhere before removing it from the database.

**Comment by matbme** [comment]
I removed the overlay directories from `/etc/almost/overlays`, created a new overlay, and now it worked properly. Something went wrong that time and now I can't reproduce it anymore

**Comment by matbme** [comment]
Okay, I think I got it. Overlays do not persist after a reboot, so when I try to discard an overlay I created prior to rebooting it fails because it isn't mounted. Correct me if I'm wrong, but I believe overlays were supposed to be remounted in the next boot, right?

**Comment by mirkobrombin** [comment]
Ya, overlays are temporary, so you must commit or discard changes before reboot

**Comment by mirkobrombin** [comment]
persistent overlays is something I'd like to implement in the near future

**Comment by matbme** [comment]
Got it. But there is still the problem that the overlay doesn't get discarded automatically, so if I don't commit or discard it, I can't create a new one because the old one is still there, but I also can't get rid of it with `almost overlay discard` because it tries to unmount something that isn't mounted and the command fails.

**Comment by mirkobrombin** [comment]
I'll try to reproduce. Can you post here the exact commands?

**Comment by matbme** [comment]
```sh
sudo almost overlay new /usr/lib
reboot
sudo almost overlay discard /usr/lib  # Will fail with invalid argument 
sudo almost overlay new /usr/lib  # Will fail because there's another overlay for the same path
```

**Comment by mirkobrombin** [comment]
fixed by https://github.com/Vanilla-OS/almost/commit/91da5cfacfa641982e7908f9e6e35e5a0f6b5b90
